linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - funlen
    - gochecknoinits
    - gocritic
    - goconst
    - gocyclo
    - goimports
    - revive
    - rowserrcheck
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - gofumpt
    - whitespace
    - errcheck

issues:
  exclude-rules:
    - path: movies.go
      linters:
        - revive
    - path: main.go
      linters:
        - revive
    - path: helpers.go
      linters:
        - errcheck
    - path: internal/validator/validator.go
      linters:
        - gofumpt

